version: '3'


services:
  generator:
    build: ./generator
    ports: ['5001:5000']
    environment:
      MONGODB_DATABASE: '${MONGODB_DATABASE}'
      MONGODB_USER: '${MONGODB_USERNAME}'
      MONGODB_PASSWORD: '${MONGODB_PASSWORD}'
      MONGODB_HOSTNAME: '${MONGODB_HOSTNAME}'
    volumes: ['./generator:/app']
    container_name: urlshortener-generator
  router:
    build: ./router
    ports: ['5002:5000']
    environment:
      MONGODB_DATABASE: '${MONGODB_DATABASE}'
      MONGODB_USER: '${MONGODB_USERNAME}'
      MONGODB_PASSWORD: '${MONGODB_PASSWORD}'
      MONGODB_HOSTNAME: '${MONGODB_HOSTNAME}'
    volumes: ['./router:/app']
    container_name: urlshortener-router
  mongodb:
    image: mongo:latest
    hostname: urlshortener
    container_name: urlshortener-mongodb
    environment:
      - MONGO_INITDB_DATABASE='${MONGO_INITDB_DATABASE}'
      - MONGO_INITDB_ROOT_USERNAME='${MONGO_INITDB_ROOT_USERNAME}'
      - MONGO_INITDB_ROOT_PASSWORD='${MONGO_INITDB_ROOT_PASSWORD}'
    ports: ['27017:27017']
